### PR TITLE
Set up e2e tests

### LINKED ISSUE #216: Add e2e UI tests
**Is your feature request related to a problem? Please describe.**
Add some end to end UI tests to verify that changes do not break the Flipt UI and that users see the expected results.

**Describe the solution you'd like**
Perhaps something like [testcafe](https://devexpress.github.io/testcafe/)? I dont know much about the 'modern' e2e Javascript testing frameworks.. but I know things I DO NOT WANT:

❌ **No** ❌ :
* Selenium or browser based tests as these are slow and error prone
* BDD testing language, just want simple easy to write expectation based tests

**Additional context**
Something that could capture screenshots when tests fail would be nice too for local development

### PR DESCRIPTION
**Pull request by jperl**
Resolves #216

To Do

- [x] set up CI
- [x] add test attributes & update tests

### CODE REVIEW

**Comment by jperl** [comment]
@markphelps This is a WIP PR, I will follow up shortly with the remaining TODOs. I started with two basic e2e tests, creating a flag and segment.

I am also recording a video as I set it up, in case you are interested in the process. This is the first video https://www.youtube.com/watch?v=Wa6MFqrf0Nc

**Comment by jperl** [comment]
Set this up to run against the docker image in CI. We can change it to start up the actual server and UI at the end.

Here is the video: https://www.youtube.com/watch?v=5r8k14MT-O0

I will work on updating the ui to have test attributes tomorrow.

**Comment by markphelps** [comment]
This is amazing. Thank you @jperl and I love the videos. What screen capture program do you use?

**Comment by jperl** [comment]
We built [playwright-video](https://github.com/qawolf/playwright-video) which uses [Chrome DevTools screencast](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast) to collect the images, and ffmpeg to construct the video.

**Comment by jperl** [comment]
@markphelps I updated the front end to have test attributes where needed to improve the selectors. The tests pass locally, but the GitHub action needs to run the latest code instead of the latest docker for them to pass.

**Comment by jperl** [comment]
> What screen capture program do you use?

The youtube videos I livestream with OBS.

**Comment by markphelps** [comment]
@jperl awesome thank you so much for your hard work! will check it out this evening and merge

When you say:
> The tests pass locally, but the GitHub action needs to run the latest code instead of the latest docker for them to pass.

Do you mean that the current [Docker image](https://github.com/markphelps/flipt/blob/master/Dockerfile) doesnt the required dependencies that you install [here](https://github.com/markphelps/flipt/pull/253/files#diff-c4f90ba82aaf8f73cccdfdeaa681e10dR22-R28)?

**Comment by markphelps** [comment]
@all-contributors please add @jperl for test and code

**Comment by jperl** [comment]
I mean the GitHub action currently spins up the docker image instead of running the server and front end for the latest code. The tests run against that.

**Comment by markphelps** [comment]
Oh gotcha. Yah i'll fix that this weekend. Thanks again for adding these tests!!!

**Comment by jperl** [comment]
My pleasure. Happy to help adding more just let me know.

**Pull request merged**
