### PR TITLE
Keep base image for production image up-to-date

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Review by markphelps — APPROVED** [review]
thanks!

**Comment by markphelps** [comment]
@all-contributors please add @sagikazarmark for code

**Comment by sagikazarmark** [comment]
Rebased from master, but Lint is still missing.

**Comment by markphelps** [comment]
> Rebased from master, but Lint is still missing.

IDK why it fails to run sometimes, but I'm not worried about it. Will merge now

**Pull request merged**
