### PR TITLE
Try to upgrade yarn dev dependencies

### PR DESCRIPTION
**Pull request by markphelps**
##  Goal

Upgrade to latest versions of JS dev dependencies

## What I Did

```shell
~/workspace/flipt/ui yarn-dev-deps
❯ yarn version
yarn version v1.17.0
```

`yarn upgrade-interactive --latest`

To upgrade all dependencies

## What Happens

When I run `yarn dev`, it opens the browser but then I get:

```javascript
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
```

In the console

## What Should Happen

No JS errors in the console when running `yarn dev`

### CODE REVIEW

**Comment by markphelps** [comment]
@christopherdiehl here's what I was talking about with the JS dev dependencies

**Comment by christopherdiehl** [comment]
Thanks for opening, I'll take a look after work!

**Comment by markphelps** [comment]
@christopherdiehl I'm still getting errors in the JS console:

Screen Shot 2019-07-16 at 8 49 13 AM

Also when I run `yarn check` I get this:

```shell
~/workspace/flipt/ui yarn-dev-deps*
❯ yarn check
yarn check v1.17.3
error "eslint-plugin-vue#eslint@^5.0.0" doesn't satisfy found match of "eslint@6.0.1"
error "extract-text-webpack-plugin#webpack@^3.1.0" doesn't satisfy found match of "webpack@4.35.3"
error "eslint-plugin-vue#vue-eslint-parser#eslint@^5.0.0" doesn't satisfy found match of "eslint@6.0.1"
warning "chokidar#fsevents#node-pre-gyp@^0.12.0" could be deduped from "0.12.0" to "node-pre-gyp@0.12.0"
error Found 3 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

I even ran `rm -rf` on my `node_modules` folder and ran `yarn` again to no avail. What am I doing wrong?

**Comment by christopherdiehl** [comment]
@markphelps I had those messages on the first run, but they went away.. I'll start over with a fresh install and see if what's going on!

**Comment by christopherdiehl** [comment]
@markphelps 

Both the eslint-plugin-vue eslint version mismatch errors are caused by the projects themselves. It appears that they bumped the requirements up to eslint v6 22 days ago, but haven't released a new version in the meantime.

The extract-text-plugin should be removed and I can definitely help with converting to the mini-css plugin. 

The error you are seeing is a webpack/babel error caused by a file using import in conjunction with module.exports. I initially thought this was a straightforward fix, but I'm unable to find where the `module.exports` is inside the codebase. Since I'm not seeing it inside the `src` folder, it leads me to believe that the error is being caused by a dependency. I can take a look, but I'm unsure how long the game of whack-a-mole will take.

Please let me know if that makes sense, and if so I'll start on the webpack import bug!

**Comment by markphelps** [comment]
Ah thank you for investigating this. I’m wondering if it makes sense to
backup and try and update to stable versions that aren’t latest? Maybe I
was too aggressive when trying to do them all in one swoop?

**Comment by christopherdiehl** [comment]
@markphelps that's my thought as well. Upgrading one package at a time (starting with webpack or babel) until you have stable releases across the board. Then wait 3 months and do it again 😞 

If it's okay with you I'll create a new branch from master and start slowly upgrading then open a new PR

**Comment by markphelps** [comment]
@christopherdiehl that would be amazing!!!

**Pull request closed without merging**
