### PR TITLE
Replaces 0.0.0.0 by 127.0.0.1 on the codebase

### PR DESCRIPTION
**Pull request by edumucelli**
As discussed in #385 this is the step 2: align the codebase to spin up the service and expect it on 127.0.0.1 instead of 0.0.0.0.
To be applied whenever @markphelps release a new version, to avoid any back-compatibility issues you may have in mind.

A new `demo.gif` is required.

### CODE REVIEW

**Comment by markphelps** [comment]
@all-contributors please add @edumucelli for code

**Comment by markphelps** [comment]
@edumucelli thanks for the PR! 

I'm getting some weird issues when trying to run locally though via `make dev`.

In the screenshots below you can see that the API is returning flag results, however the UI can't seem to render them. I'm wondering if it has to do with some cross-origin issues resulting from these changes?

Screen Shot 2021-02-19 at 9 45 51 AM

Screen Shot 2021-02-19 at 9 45 42 AM

Screen Shot 2021-02-19 at 9 46 40 AM

**Comment by edumucelli** [comment]
Hmm, indeed, I can reproduce it. Somehow when setting `"127.0.0.1:8080"` on `api.js` is not working as expected. I have basically on knowledge on JS frameworks. I will see if I can debug it somehow. Thanks for the feedback.

**Comment by markphelps** [comment]
> Hmm, indeed, I can reproduce it. Somehow when setting `"127.0.0.1:8080"` on `api.js` is not working as expected. I have basically on knowledge on JS frameworks. I will see if I can debug it somehow. Thanks for the feedback.

No prob. I will look into this as well. I'm starting to think that this issue may be why I chose `0.0.0.0` in the first place.. but there has to be a solution.. so I will keep 👀

**Comment by markphelps** [comment]
@edumucelli FYI I think #396 will fix the issue we were seeing, so after that is merged this PR should be good to go

**Comment by edumucelli** [comment]
> @edumucelli FYI I think #396 will fix the issue we were seeing, so after that is merged this PR should be good to go

That is neat! Looking forward to see it merged!

**Comment by markphelps** [comment]
Thanks @edumucelli !

**Pull request merged**
