### PR TITLE
Disallow colons

### PR DESCRIPTION
**Pull request by markphelps**
Fixes: #262 

Screen Shot 2020-05-22 at 10 16 40 AM

### CODE REVIEW

**Comment by markphelps** [comment]
@jperl 👋🏻  I was wondering if you could help me debug why my QAWolf Integration Test is failing here: https://github.com/markphelps/flipt/runs/709580872?check_suite_focus=true#step:10:115

I am trying to merge the `qawolf.yml` workflow that you created with my existing `integration-test.yml` workflow, so that QAWolf will always run against the latest (changed) code, instead of having to use the Docker image that I publish on release.

It seems that QAWolf/Playwright is getting a `404 Not Found` when trying to navigate to `http://0.0.0.0:8080` within the container.. however I can't think why that would be the case, as I wait for the host to be available here: https://github.com/markphelps/flipt/pull/291/files#diff-082650297ecabbdf711809e2fcc86731R21

Attached is the zip containing the video from ffmpeg (which is awesome btw. super helpful for debugging):

[qawolf-1.zip](https://github.com/markphelps/flipt/files/4682839/qawolf-1.zip)

Any help would be greatly appreciated!

**Comment by jperl** [comment]
@markphelps Can you run `curl http://0.0.0.0:8080` after the wait on so we can see what the output is?

**Comment by markphelps** [comment]
@jperl I figured it out, I wasn't 'building the ui' in the Integration Test workflow.. so it had nothing to serve, hence the 404.

Thanks!

**Comment by jperl** [comment]
Ok great. Glad you figured it out 🙏. Thanks for the update.

**Pull request merged**
